=== aditya-kuruganti/test-repo/api/schemas/request/966_request_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "operationId": {
      "type": "string"
    },
    "languageCode": {
      "type": "string"
    },
    "transactionCode": {
      "type": "string"
    },
    "userId": {
      "type": "string"
    },
    "givexNumber": {
      "type": "string"
    },
    "serialNumber": {
      "type": "string"
    },
    "cardIso": {
      "type": "string"
    },
    "historyType": {
      "type": "string"
    },
    "startDate": {
      "type": "string"
    },
    "endDate": {
      "type": "string"
    },
    "transactionType": {
      "type": "string"
    },
    "additionalData": {
      "type": "string"
    }
  },
  "required": [
    "operationId",
    "languageCode",
    "transactionCode",
    "userId",
    "givexNumber",
    "serialNumber",
    "cardIso",
    "historyType"
  ]
}

=== aditya-kuruganti/test-repo/lp-api/api/examples/request/966_request_example.json
{
  "operationId": "966",
  "languageCode": "0",
  "transactionCode": "2000405",
  "userId": "171052",
  "givexNumber" : "633701234528219529",
  "serialNumber" : "",
  "cardIso" : "",
  "historyType" : "",
  "startDate" : "12-12-2011",
  "endDate" : "12-12-2011",
  "transactionType" : "",
  "additionalData": "9121"
}
