=== aditya-kuruganti/test-repo/lp-system-api/api/schemas/response/910_response_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "operationId": {
      "type": "string"
    },
    "transactionCode": {
      "type": "string"
    },
    "result": {
      "type": "string"
    },
    "givexTransactionReferenceTo": {
      "type": "string"
    },
    "errorMessage": {
      "type": "null"
    },
    "certificateBalance": {
      "type": "string"
    },
    "certificateExpirationDate": {
      "type": "string"
    },
    "receiptMessage": {
      "type": "string"
    },
    "givexPointsTransactionReferenceTo": {
      "type": "string"
    },
    "pointsBalance": {
      "type": "string"
    },
    "securityCode": {
      "type": "string"
    },
    "isoSerialFrom": {
      "type": "string"
    },
    "currencyCode": {
      "type": "string"
    },
    "isoSerialTo": {
      "type": "string"
    },
    "givexTransactionReferenceFrom": {
      "type": "string"
    },
    "givexPointsTransactionReferenceFrom": {
      "type": "string"
    }
  },
  "required": [
    "operationId",
    "transactionCode",
    "result"
  ]
}

=== aditya-kuruganti/test-repo/lp-system-api/api/examples/response/910_response_example.json
{
	"operationId" : "910",
	"transactionCode" : "2000405",
	"result" : "0",
	"givexTransactionReferenceTo" : "0.00",
	"errorMessage" : null,
  	"certificateBalance" : "12.45",
  	"certificateExpirationDate" : "",
  	"receiptMessage" : "",
  	"givexPointsTransactionReferenceTo" : "",
  	"pointsBalance" : "",
  	"securityCode" : "",
	"isoSerialFrom" : "633780-28219529",
	"currencyCode" : "",
	"isoSerialTo" : "633780-28219529",
	"givexTransactionReferenceFrom" : "0.00",
	"givexPointsTransactionReferenceFrom" : "34.23"
}
