=== aditya-kuruganti/test-repo/lp-system-api/api/schemas/response/912_response_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "operationId": {
      "type": "string"
    },
    "transactionCode": {
      "type": "string"
    },
    "result": {
      "type": "string"
    },
    "givexTransactionReference": {
      "type": "string"
    },
    "errorMessage": {
      "type": "null"
    },
    "pointsBalance": {
      "type": "string"
    },
    "certificateBalance": {
      "type": "string"
    },
    "memberName": {
      "type": "string"
    },
    "receiptMessage": {
      "type": "string"
    },
    "isoSerial": {
      "type": "string"
    },
    "rewardReference": {
      "type": "string"
    }
  },
  "required": [
    "operationId",
    "transactionCode",
    "result",
    "givexTransactionReference",
    "errorMessage",
    "pointsBalance",
    "certificateBalance",
    "memberName",
    "isoSerial"
  ]
}

=== aditya-kuruganti/test-repo/lp-api/api/examples/response/912_response_example.json
{
	"operationId" : "912",
	"transactionCode" : "2000405",
	"result" : "0",
	"givexTransactionReference" : "0.00",
	"errorMessage" : null,
 	"pointsBalance" : "12.45",
  	"certificateBalance" : "12.45",
  	"memberName" : "",
  	"receiptMessage" : "",
	"isoSerial" : "633780-28219529",
	"rewardReference" : ""
}
