=== aditya-kuruganti/test-repo/lp-process-api/api/schemas/response/913_response_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "operationId": {
      "type": "string"
    },
    "transactionCode": {
      "type": "string"
    },
    "result": {
      "type": "string"
    },
    "givexTransactionReference": {
      "type": "string"
    },
    "errorMessage": {
      "type": "null"
    },
    "certificateBalance": {
      "type": "string"
    },
    "pointsCancelled": {
      "type": "string"
    },
    "pointsBalance": {
      "type": "string"
    },
    "memberName": {
      "type": "string"
    },
    "isoSerial": {
      "type": "string"
    },
    "receiptMessage": {
      "type": "string"
    }
  },
  "required": [
    "operationId",
    "transactionCode",
    "result",
    "givexTransactionReference",
    "errorMessage",
    "certificateBalance",
    "pointsCancelled",
    "pointsBalance",
    "memberName",
    "isoSerial",
    "receiptMessage"
  ]
}

=== aditya-kuruganti/test-repo/lp-api/api/examples/response/913_response_example.json
{
	"operationId" : "913",
	"transactionCode" : "2000405",
	"result" : "0",
	"givexTransactionReference" : "0.00",
	"errorMessage" : null,
  	"certificateBalance" : "12.45",
  	"pointsCancelled" : "100",
  	"pointsBalance" : "200",
  	"memberName" : "",
	"isoSerial" : "633780-28219529",
	"receiptMessage" : ""
}
