=== aditya-kuruganti/test-repo/lp-api/api/schemas/response/902_response_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "operationId": {
      "type": "string"
    },
    "transactionCode": {
      "type": "string"
    },
    "result": {
      "type": "string"
    },
    "givexTransactionReference": {
      "type": "string"
    },
    "errorMessage": {
      "type": "null"
    },
    "amountRedeemed": {
      "type": "string"
    },
    "certificateBalance": {
      "type": "string"
    },
    "certificateExpirationDate": {
      "type": "string"
    },
    "receiptMessage": {
      "type": "string"
    },
    "pointsAdded": {
      "type": "string"
    },
    "pointsBalance": {
      "type": "string"
    },
    "discountAmount": {
      "type": "string"
    },
    "isoSerial": {
      "type": "string"
    },
    "couponReference": {
      "type": "string"
    },
    "cashRewardReference": {
      "type": "string"
    }
  },
  "required": [
    "operationId",
    "transactionCode",
    "result",
    "givexTransactionReference",
    "errorMessage",
    "amountRedeemed",
    "certificateBalance",
    "certificateExpirationDate",
    "isoSerial",
    "couponReference",
    "cashRewardReference"
  ]
}

=== aditya-kuruganti/test-repo/lp-api/api/examples/response/902_response_example.json
{
	"operationId" : "902",
	"transactionCode" : "2000405",
	"result" : "0",
	"givexTransactionReference" : "0.00",
	"errorMessage" : null,
	"amountRedeemed" : "23.23",
  	"certificateBalance" : "12.45",
  	"certificateExpirationDate" : "",
  	"receiptMessage" : "",
  	"pointsAdded" : "",
  	"pointsBalance" : "",
  	"discountAmount" : "",
	"isoSerial" : "633780-28219529",
	"couponReference" : "",
	"cashRewardReference" : ""
}
