=== aditya-kuruganti/test-repo/lp-api/api/schemas/response/911_response_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "operationId": {
      "type": "string"
    },
    "transactionCode": {
      "type": "string"
    },
    "result": {
      "type": "string"
    },
    "givexTransactionReference": {
      "type": "string"
    },
    "errorMessage": {
      "type": "null"
    },
    "pointsAdded": {
      "type": "string"
    },
    "pointsBalance": {
      "type": "string"
    },
    "certificateBalance": {
      "type": "string"
    },
    "memberName": {
      "type": "string"
    },
    "receiptMessage": {
      "type": "string"
    },
    "discountAmount": {
      "type": "string"
    },
    "isoSerial": {
      "type": "string"
    },
    "unitBalance": {
      "type": "string"
    },
    "loyaltyBalance": {
      "type": "string"
    }
  },
  "required": [
    "operationId",
    "transactionCode",
    "result",
    "givexTransactionReference",
    "errorMessage",
    "pointsAdded",
    "pointsBalance",
    "certificateBalance",
    "memberName",
    "isoSerial",
    "unitBalance",
    "loyaltyBalance"
  ]
}

=== aditya-kuruganti/test-repo/lp-api/api/examples/response/911_response_example.json
{
	"operationId" : "911",
	"transactionCode" : "2000405",
	"result" : "0",
	"givexTransactionReference" : "0.00",
	"errorMessage" : null,
  "pointsAdded" : "32.21",
  "pointsBalance" : "12.45",
  "certificateBalance" : "12.45",
  "memberName" : "",
  "receiptMessage" : "",
  "discountAmount" : "12.34",
	"isoSerial" : "633780-28219529",
	"unitBalance" : "45.43",
  "loyaltyBalance" : "45.67"
}
