=== aditya-kuruganti/test-repo/lp-api/api/schemas/response/950_response_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "operationId": {
      "type": "string"
    },
    "transactionCode": {
      "type": "string"
    },
    "result": {
      "type": "string"
    },
    "customerId": {
      "type": "string"
    },
    "errorMessage": {
      "type": "string"
    },
    "registrationDate": {
      "type": "string"
    },
    "customer": {
      "type": "string"
    },
    "customerLogin": {
      "type": "string"
    },
    "customerTitle": {
      "type": "string"
    },
    "customerFirstName": {
      "type": "string"
    },
    "customerMiddleName": {
      "type": "string"
    },
    "customerLastName": {
      "type": "string"
    },
    "customerGender": {
      "type": "string"
    },
    "customerBirthdate": {
      "type": "string"
    },
    "customerAddress": {
      "type": "string"
    },
    "customerCity": {
      "type": "string"
    },
    "customerProvince": {
      "type": "string"
    },
    "customerCounty": {
      "type": "string"
    },
    "customerCountry": {
      "type": "string"
    },
    "customerPostalCode": {
      "type": "string"
    },
    "customerPhone": {
      "type": "string"
    },
    "customerDiscount": {
      "type": "string"
    },
    "promotionOptIn": {
      "type": "string"
    },
    "customerEmail": {
      "type": "string"
    },
    "customerMobile": {
      "type": "string"
    },
    "customerCompany": {
      "type": "string"
    },
    "messageType": {
      "type": "string"
    },
    "messageDeliveryMethod": {
      "type": "string"
    }
  },
  "required": [
    "operationId",
    "transactionCode",
    "result",
    "customerId",
    "errorMessage",
    "registrationDate",
    "customer",
    "customerLogin",
    "customerTitle",
    "customerFirstName",
    "customerMiddleName",
    "customerLastName",
    "customerGender",
    "customerBirthdate",
    "customerAddress",
    "customerCity",
    "customerProvince",
    "customerCounty",
    "customerCountry",
    "customerPostalCode",
    "customerPhone",
    "customerDiscount",
    "promotionOptIn",
    "customerEmail",
    "customerMobile",
    "customerCompany",
    "messageType",
    "messageDeliveryMethod"
  ]
}

=== aditya-kuruganti/test-repo/lp-api/api/examples/response/950_response_example.json
{
  "operationId": "950",
  "transactionCode": "69",
  "result": "0",
  "customerId": "",
  "errorMessage": "null",
  "registrationDate": "",
  "customer": "abc",
  "customerLogin": "",
  "customerTitle": "Mr",
  "customerFirstName": "Abc",
  "customerMiddleName" : "foo",
  "customerLastName" : "bar",
   "customerGender" : "male",
   "customerBirthdate" : "21-12-1990",
   "customerAddress" : "abc",
   "customerCity" : "xyz",
   "customerProvince" : "xyz",
   "customerCounty" : "xyz",
   "customerCountry" : "UK",
   "customerPostalCode" : "xyz",
   "customerPhone" : "xyz",
   "customerDiscount" : "xyz",
   "promotionOptIn" : "",
   "customerEmail" : "abc@xyz.com", 
   "customerMobile" : "",
   "customerCompany" : "",
   "messageType" : "", 
   "messageDeliveryMethod" : ""
   
}
