=== aditya-kuruganti/test-repo/lp-api/api/schemas/request/947_request_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "operationId": {
      "type": "string"
    },
    "languageCode": {
      "type": "string"
    },
    "transactionCode": {
      "type": "string"
    },
    "userId": {
      "type": "string"
    },
    "password": {
      "type": "string"
    },
    "customerLogin": {
      "type": "string"
    },
    "customerNewLogin": {
      "type": "string"
    },
    "customerPassword": {
      "type": "string"
    },
    "customerTitle": {
      "type": "string"
    },
    "customerFirstName": {
      "type": "string"
    },
    "customerMiddleName": {
      "type": "string"
    },
    "customerLastName": {
      "type": "string"
    },
    "customerGender": {
      "type": "string"
    },
    "customerBirthdate": {
      "type": "string"
    },
    "customerAddress": {
      "type": "string"
    },
    "customerAddress2": {
      "type": "string"
    },
    "customerCity": {
      "type": "string"
    },
    "customerProvince": {
      "type": "string"
    },
    "customerCounty": {
      "type": "string"
    },
    "customerCountry": {
      "type": "string"
    },
    "customerPostalCode": {
      "type": "string"
    },
    "customerEmail": {
      "type": "string"
    },
    "customerPhone": {
      "type": "string"
    },
    "customerDiscount": {
      "type": "string"
    },
    "promotionOptIn": {
      "type": "string"
    },
    "customerMobile": {
      "type": "string"
    },
    "customerCompany": {
      "type": "string"
    }
  },
  "required": [
    "operationId",
    "languageCode",
    "transactionCode",
    "userId",
    "password",
    "customerLogin",
    "customerNewLogin",
    "customerPassword",
    "customerTitle",
    "customerFirstName",
    "customerMiddleName",
    "customerLastName",
    "customerGender",
    "customerBirthdate",
    "customerAddress",
    "customerAddress2",
    "customerCity",
    "customerProvince",
    "customerCounty",
    "customerCountry",
    "customerPostalCode",
    "customerEmail",
    "customerPhone",
    "customerDiscount",
    "promotionOptIn",
    "customerMobile",
    "customerCompany"
  ]
}

=== aditya-kuruganti/test-repo/lp-api/api/examples/request/947_request_example.json
{
  "operationId": "947",
  "languageCode": "en",
  "transactionCode": "69",
  "userId": "1:25",
  "password": "1234:4321",
  "customerLogin": "10111",
  "customerNewLogin": "",
  "customerPassword": "xxxx",
  "customerTitle": "Mr",
  "customerFirstName": "koteswararao",
  "customerMiddleName": "",
  "customerLastName": "sunkavalli",
  "customerGender": "Male",
  "customerBirthdate": "YYYY-MM-DD",
  "customerAddress": "23 Anyroad St.,Suite 100|London|GU1 3UY|UK|Greater London",
  "customerAddress2": "23 Anyroad St.,Suite 100|London|GU1 3UY|UK|Greater London",
  "customerCity": "London",
  "customerProvince": "North Yorkshire",
  "customerCounty": "",
  "customerCountry": "",
  "customerPostalCode": "",
  "customerEmail": "koteswararao.sunkavalli@whishworks.com",
  "customerPhone": "",
  "customerDiscount": "",
  "promotionOptIn": "",
  "customerMobile": "",
  "customerCompany": ""
}
